spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/dev_database
    username: developer
    password: 12345678
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false

server:
  port: 8000
